services:
  worker_processor:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: worker-processor:latest
    restart: "no" #sob demanda
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    networks:
      - net

networks:
  net:
    external: true