services:
  worker_processor:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: worker-processor
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    networks:
      - net
    environment:
      - ENVIRONMENT=production

networks:
  net:
    external: true